auto: true

markdown: rdiscount
pygments: true
paginate: 8
permalink: /:title

title: SunWeicheng.com
url: http://SunWeicheng.com
feed: /atom.xml
author_info: <a href="http://sunweichneg.com/">SunWeicheng</a>
